---
title: "hw03-minjeong-jeong"
author: "Minjeong Jeong"
date: "2018³â 3¿ù 20ÀÏ"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error= TRUE, fig.path = 'images/')
```

```{r}
library(ggplot2)
```

```{r importing data}
nba_players <- read.csv(file = "nba2017-roster.csv", stringsAsFactors = FALSE)
```

#2 Pipelines and Redirection: 
######FYI:I'm a Window user
```  
 *2.1  
 
 cut -d "," -f 2 nba2017-roster.csv | sort -u > team-names.txt  
 
 head -n 5 team-names.txt  
 
 "ATL"  
 
 "BOS"  
 
 "BRK"  
 
 "CHI"  
 
 "CHO"  
   
 *2.2  
 
 cut -d "," -f 3 nba2017-roster.csv | tail +2| sort -u > position-names.txt  
 
 head -n5 position-names.txt  
 
 "C"  
 
 "PF"  
 
 "PG"  
 
 "SF"  
 
 "SG"  
   
 *2.3  
 
 cut -d "," -f 7 nba2017-roster.csv|tail +2 | sort -n | uniq -c > experience-counts.txt  
 
 head -n 5 experience-counts.txt  
 
 80 0  
 
 52 1  
 
 46 2  
 
 36 3  
 
 35 4  
   
 *2.4  
 
 egrep 'LAC|team' nba2017-roster.csv > LAC.csv  
 
 cat LAC.csv  
 
 "player","team","position","height","weight","age","experience","salary"  
 
 "Alan Anderson","LAC","SF",78,220,34,7,1315448  
 
 "Austin Rivers","LAC","SG",76,200,24,4,1.1e+07  
 
 "Blake Griffin","LAC","PF",82,251,27,6,20140838  
 
 "Brandon Bass","LAC","PF",80,250,31,11,1551659  
 
 "Brice Johnson","LAC","PF",82,230,22,0,1273920  
 
 "Chris Paul","LAC","PG",72,175,31,11,22868828  
 
 "DeAndre Jordan","LAC","C",83,265,28,8,21165675  
 
 "Diamond Stone","LAC","C",83,255,19,0,543471  
 
 "J.J. Redick","LAC","SG",76,190,32,10,7377500  
 
 "Jamal Crawford","LAC","SG",77,200,36,16,13253012  
 
 "Luc Mbah a Moute","LAC","SF",80,230,30,8,2203000  
 
 "Marreese Speights","LAC","C",82,255,29,8,1403611  
 
 "Paul Pierce","LAC","SF",79,235,39,18,3500000  
 
 "Raymond Felton","LAC","PG",73,205,32,11,1551659  
 
 "Wesley Johnson","LAC","SF",79,215,29,6,5628000  
 
 *2.5  
 
 grep 'LAL' nba2017-roster.csv | cut -d "," -f 6 | sort| uniq -c  
 
 2 19  
 
 1 20  
 
 2 22  
 
 3 24  
 
 2 25  
 
 2 30  
 
 2 31  
 
 1 37  
 
 *2.6  
 
 grep "CLE" nba2017-roster.csv | wc -l  
 
 15  
   
 *2.7  
 
 egrep 'GSW|team' nba2017-roster.csv | cut -d "," -f 1,4,5 > gsw-height-weight.csv  
 
 cat gsw-height-weight.csv  
 
 "player","height","weight"  
 
 "Andre Iguodala",78,215  
 
 "Damian Jones",84,245  
 
 "David West",81,250  
 
 "Draymond Green",79,230  
 
 "Ian Clark",75,175  
 
 "James Michael McAdoo",81,230  
 
 "JaVale McGee",84,270  
 
 "Kevin Durant",81,240  
 
 "Kevon Looney",81,220  
 
 "Klay Thompson",79,215  
 
 "Matt Barnes",79,226  
 
 "Patrick McCaw",79,185  
 
 "Shaun Livingston",79,192  
 
 "Stephen Curry",75,190  
 
 "Zaza Pachulia",83,270  
 
 *2.8  
 
 cut -d ',' -f 1,8 nba2017-roster.csv| head -n 1 > temp.csv  
 
 sort -t "," -k 8 -n -r nba2017-roster.csv| cut -d "," -f 1,8| head -n 10 > top10-salaries.csv  
 
 cat top10-salaries.csv >> temp.csv  
 
 rm top10-salaries.csv  
 
 mv temp.csv top10-salaries.csv  
 
 cat top10-salaries.csv  

 "player","salary"  
 
 "LeBron James",30963450  
 
 "Russell Westbrook",26540100  
 
 "Mike Conley",26540100  
 
 "Kevin Durant",26540100  
 
 "James Harden",26540100  
 
 "DeMar DeRozan",26540100  
 
 "Al Horford",26540100  
 
 "Carmelo Anthony",24559380  
 
 "Damian Lillard",24328425  
 
 "Dwyane Wade",23200000  
 
 ```  
 
#Binomial Probability Functions
```{r source}
source("code/binomial-functions.R")
```

```{r binomialprob1}
#getting 'six': 3 successes in 10 trials
bin_probability(10,3,(1/6))
```

```{r binomialplot1}
#binomial distribution:10 trials to get 'six'
bin_distribution(10,0.25)
binomial_hist <- bin_distribution( 10, 0.25)
barplot(binomial_hist$probability, names.arg = binomial_hist$success,
        main = "Binomial Distribution", xlab="Success", ylab="Probability",
        col = c("pink"), border = "black")
```

```{r  binomialprob2}
#prob of geeting more than 3 heads in 5 tosses
probability <- 0
for (i in 4:5) {
  probability = bin_probability( 5, i, 0.35) + probability
}
probability
```

```{r binomialplot2}
#binomial distribution:15 trials to obtain head

binomial_plot <- bin_distribution(15, 0.35)
ggplot(data = binomial_plot, aes(success, probability)) +
         geom_point()+
         geom_line()+
         ggtitle("Binomial Distribution")+
        theme_minimal()
```